"""initial schema

Revision ID: 4d790816dda4
Revises: 
Create Date: 2026-09-24 01:36:48.235895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d790816dda4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('trained_on', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_challenges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_challenges_phone_hash'), ['phone_hash'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sync_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('result_ref', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_jobs_device_id'), ['device_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone_hash'), ['phone_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('helpdesk_callbacks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('template', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('to', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_ref', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('operators',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('csc_id', sa.String(length=64), nullable=True),
    sa.Column('shg_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('region', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('buyer_id', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('ondc_transaction_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('address', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('payment_method', sa.String(length=8), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('logistics_fee', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('delivery_estimate_days', sa.Integer(), nullable=True),
    sa.Column('tracking', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('history', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_ondc_transaction_id'), ['ondc_transaction_id'], unique=False)

    op.create_table('uploads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('received', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('artisans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_native', sa.String(length=120), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('craft_type', sa.String(length=120), nullable=True),
    sa.Column('years_practice', sa.Integer(), nullable=True),
    sa.Column('story_text', sa.Text(), nullable=True),
    sa.Column('story_audio_url', sa.String(length=512), nullable=True),
    sa.Column('story_translations', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('pehchan_id', sa.String(length=255), nullable=True),
    sa.Column('pehchan_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('shg_name', sa.String(length=160), nullable=True),
    sa.Column('csc_id', sa.String(length=64), nullable=True),
    sa.Column('cluster', sa.String(length=160), nullable=True),
    sa.Column('gi_tag', sa.String(length=160), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('consent_flags', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('onboarded_by_operator_id', sa.String(length=32), nullable=True),
    sa.Column('operator_attestation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['onboarded_by_operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('artisans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artisans_cluster'), ['cluster'], unique=False)
        batch_op.create_index(batch_op.f('ix_artisans_state'), ['state'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_order_id', sa.String(length=80), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)

    op.create_table('payouts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('artisan_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('gross', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('logistics', sa.Float(), nullable=False),
    sa.Column('net', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payouts_artisan_id'), ['artisan_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('artisan_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('short_title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('translations', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('needs_review_fields', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('pipeline', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('compare_at_price', sa.Float(), nullable=True),
    sa.Column('rank_score', sa.Float(), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_via', sa.String(length=8), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('device_edited_fields', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('captured_offline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderation_flag', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_artisan_id'), ['artisan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_status'), ['status'], unique=False)

    op.create_table('scheme_links',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scheme', sa.String(length=16), nullable=False),
    sa.Column('artisan_id', sa.String(length=32), nullable=True),
    sa.Column('cluster', sa.String(length=160), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('buyer_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'product_id')
    )
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_items_buyer_id'), ['buyer_id'], unique=False)

    op.create_table('certificates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('qr_url', sa.String(length=512), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('buyer_id', sa.String(length=32), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('artisan_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=True),
    sa.Column('payout_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('memo', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_artisan_id'), ['artisan_id'], unique=False)

    op.create_table('ondc_sync',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_payload', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('price_quotes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('inputs', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('breakdown', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('market_low', sa.Float(), nullable=False),
    sa.Column('market_high', sa.Float(), nullable=False),
    sa.Column('market_mid', sa.Float(), nullable=False),
    sa.Column('recommended', sa.Float(), nullable=False),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('artisan_share_amount', sa.Float(), nullable=False),
    sa.Column('artisan_share_pct', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_quotes_product_id'), ['product_id'], unique=False)

    op.create_table('product_media',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_media_product_id'), ['product_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('artisan_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('price_quote_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisans.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['price_quote_id'], ['price_quotes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_artisan_id'), ['artisan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('order_item_id', sa.String(length=32), nullable=True),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('buyer_id', sa.String(length=32), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_product_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_artisan_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('product_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_media_product_id'))

    op.drop_table('product_media')
    with op.batch_alter_table('price_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_quotes_product_id'))

    op.drop_table('price_quotes')
    op.drop_table('ondc_sync')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_artisan_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_ts'))
        batch_op.drop_index(batch_op.f('ix_events_product_id'))

    op.drop_table('events')
    op.drop_table('certificates')
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_items_buyer_id'))

    op.drop_table('cart_items')
    op.drop_table('scheme_links')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_status'))
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.drop_index(batch_op.f('ix_products_artisan_id'))

    op.drop_table('products')
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payouts_artisan_id'))

    op.drop_table('payouts')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))

    op.drop_table('payments')
    with op.batch_alter_table('artisans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artisans_state'))
        batch_op.drop_index(batch_op.f('ix_artisans_cluster'))

    op.drop_table('artisans')
    op.drop_table('uploads')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_ondc_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_orders_buyer_id'))

    op.drop_table('orders')
    op.drop_table('operators')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    op.drop_table('helpdesk_callbacks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone_hash'))

    op.drop_table('users')
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_jobs_device_id'))

    op.drop_table('sync_jobs')
    op.drop_table('settings')
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_challenges_phone_hash'))

    op.drop_table('otp_challenges')
    op.drop_table('model_versions')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
