"""Multilingual craft vocabulary used by the rule-based (mock / fallback) NLU and template translator.

Each entry: canonical key -> {"match": [surface forms in any script], "<lang>": display label}.
Latin surface forms are matched on word boundaries; Indic-script forms as substrings.
"""

CATEGORIES = [
    "Textiles & Handloom",
    "Pottery & Ceramics",
    "Metalcraft",
    "Woodcraft",
    "Bamboo & Cane",
    "Jewellery",
    "Paintings & Folk Art",
    "Leather",
    "Stone Craft",
    "Toys & Dolls",
    "Home Décor",
    "Other",
]

CATEGORY_LABELS = {
    "Textiles & Handloom": {"hi": "वस्त्र और हथकरघा", "bn": "বস্ত্র ও তাঁত", "mr": "वस्त्र आणि हातमाग"},
    "Pottery & Ceramics": {"hi": "मिट्टी और चीनी मिट्टी के बर्तन", "bn": "মৃৎশিল্প", "mr": "मातीकाम"},
    "Metalcraft": {"hi": "धातु शिल्प", "bn": "ধাতুশিল্প", "mr": "धातुकाम"},
    "Woodcraft": {"hi": "काष्ठ शिल्प", "bn": "কাঠের কাজ", "mr": "लाकूडकाम"},
    "Bamboo & Cane": {"hi": "बाँस और बेंत", "bn": "বাঁশ ও বেত", "mr": "बांबू आणि वेत"},
    "Jewellery": {"hi": "आभूषण", "bn": "গয়না", "mr": "दागिने"},
    "Paintings & Folk Art": {"hi": "चित्रकला और लोक कला", "bn": "চিত্রকলা ও লোকশিল্প", "mr": "चित्रकला आणि लोककला"},
    "Leather": {"hi": "चमड़ा शिल्प", "bn": "চামড়ার কাজ", "mr": "चर्मकला"},
    "Stone Craft": {"hi": "पत्थर शिल्प", "bn": "পাথরের কাজ", "mr": "दगडकाम"},
    "Toys & Dolls": {"hi": "खिलौने और गुड़िया", "bn": "খেলনা ও পুতুল", "mr": "खेळणी आणि बाहुल्या"},
    "Home Décor": {"hi": "गृह सज्जा", "bn": "গৃহসজ্জা", "mr": "गृहसजावट"},
    "Other": {"hi": "अन्य", "bn": "অন্যান্য", "mr": "इतर"},
}

# product type -> category, labels
PRODUCT_TYPES = {
    "vase": {"match": ["vase", "flower pot", "phooldan", "guldasta", "फूलदान", "गुलदस्ता", "ফুলদানি", "फुलदाणी"],
             "category": "Pottery & Ceramics", "en": "Vase", "hi": "फूलदान", "bn": "ফুলদানি", "mr": "फुलदाणी"},
    "pot": {"match": ["pot", "matka", "handi", "मटका", "हांडी", "घड़ा", "হাঁড়ি", "मडके"],
            "category": "Pottery & Ceramics", "en": "Pot", "hi": "मटका", "bn": "হাঁড়ি", "mr": "मडके"},
    "bowl": {"match": ["bowl", "katori", "कटोरा", "कटोरी", "বাটি", "वाटी"],
             "category": "Pottery & Ceramics", "en": "Bowl", "hi": "कटोरा", "bn": "বাটি", "mr": "वाटी"},
    "plate": {"match": ["plate", "thali", "थाली", "प्लेट", "থালা", "ताट"],
              "category": "Pottery & Ceramics", "en": "Plate", "hi": "थाली", "bn": "থালা", "mr": "ताट"},
    "mug": {"match": ["mug", "cup", "kulhad", "कुल्हड़", "कप", "কাপ"],
            "category": "Pottery & Ceramics", "en": "Mug", "hi": "कप", "bn": "কাপ", "mr": "कप"},
    "tile": {"match": ["tile", "tiles", "टाइल"],
             "category": "Pottery & Ceramics", "en": "Tile", "hi": "टाइल", "bn": "টালি", "mr": "टाइल"},
    "saree": {"match": ["saree", "sari", "साड़ी", "साडी", "শাড়ি", "साडी"],
              "category": "Textiles & Handloom", "en": "Saree", "hi": "साड़ी", "bn": "শাড়ি", "mr": "साडी"},
    "stole": {"match": ["stole", "dupatta", "दुपट्टा", "ओढ़नी", "স্টোল", "ওড়না", "ओढणी"],
              "category": "Textiles & Handloom", "en": "Stole", "hi": "दुपट्टा", "bn": "ওড়না", "mr": "ओढणी"},
    "shawl": {"match": ["shawl", "शॉल", "शाल", "শাল"],
              "category": "Textiles & Handloom", "en": "Shawl", "hi": "शॉल", "bn": "শাল", "mr": "शाल"},
    "kurta": {"match": ["kurta", "कुर्ता", "কুর্তা"],
              "category": "Textiles & Handloom", "en": "Kurta", "hi": "कुर्ता", "bn": "কুর্তা", "mr": "कुर्ता"},
    "fabric": {"match": ["fabric", "cloth", "kapda", "कपड़ा", "थान", "কাপড়", "कापड"],
               "category": "Textiles & Handloom", "en": "Fabric", "hi": "कपड़ा", "bn": "কাপড়", "mr": "कापड"},
    "cushion_cover": {"match": ["cushion cover", "cushion", "कुशन"],
                      "category": "Home Décor", "en": "Cushion Cover", "hi": "कुशन कवर", "bn": "কুশন কভার", "mr": "कुशन कव्हर"},
    "bedsheet": {"match": ["bedsheet", "bed sheet", "चादर", "চাদর"],
                 "category": "Textiles & Handloom", "en": "Bedsheet", "hi": "चादर", "bn": "চাদর", "mr": "चादर"},
    "quilt": {"match": ["quilt", "kantha", "रजाई", "কাঁথা"],
              "category": "Textiles & Handloom", "en": "Quilt", "hi": "रजाई", "bn": "কাঁথা", "mr": "गोधडी"},
    "bag": {"match": ["bag", "jhola", "thaila", "थैला", "झोला", "बैग", "ব্যাগ", "पिशवी"],
            "category": "Textiles & Handloom", "en": "Bag", "hi": "थैला", "bn": "ব্যাগ", "mr": "पिशवी"},
    "figurine": {"match": ["figurine", "statue", "idol", "murti", "मूर्ति", "মূর্তি", "मूर्ती"],
                 "category": "Metalcraft", "en": "Figurine", "hi": "मूर्ति", "bn": "মূর্তি", "mr": "मूर्ती"},
    "horse": {"match": ["horse", "ghoda", "घोड़ा", "ঘোড়া", "घोडा"],
              "category": "Metalcraft", "en": "Horse Figurine", "hi": "घोड़ा", "bn": "ঘোড়া", "mr": "घोडा"},
    "elephant": {"match": ["elephant", "haathi", "hathi", "हाथी", "হাতি", "हत्ती"],
                 "category": "Metalcraft", "en": "Elephant Figurine", "hi": "हाथी", "bn": "হাতি", "mr": "हत्ती"},
    "lamp": {"match": ["lamp", "diya", "deepak", "दीया", "दीपक", "প্রদীপ", "दिवा"],
             "category": "Home Décor", "en": "Lamp", "hi": "दीया", "bn": "প্রদীপ", "mr": "दिवा"},
    "bell": {"match": ["bell", "ghanti", "घंटी", "ঘণ্টা"],
             "category": "Metalcraft", "en": "Bell", "hi": "घंटी", "bn": "ঘণ্টা", "mr": "घंटा"},
    "necklace": {"match": ["necklace", "haar", "हार", "माला", "হার", "नेकलेस"],
                 "category": "Jewellery", "en": "Necklace", "hi": "हार", "bn": "হার", "mr": "हार"},
    "earrings": {"match": ["earrings", "earring", "jhumka", "jhumke", "झुमके", "झुमका", "बाली", "কানের দুল", "कानातले"],
                 "category": "Jewellery", "en": "Earrings", "hi": "झुमके", "bn": "কানের দুল", "mr": "कानातले"},
    "bangle": {"match": ["bangle", "bangles", "chudi", "चूड़ी", "चूड़ियाँ", "কাঁকন", "बांगडी"],
               "category": "Jewellery", "en": "Bangles", "hi": "चूड़ियाँ", "bn": "চুড়ি", "mr": "बांगड्या"},
    "basket": {"match": ["basket", "tokri", "टोकरी", "ঝুড়ি", "टोपली"],
               "category": "Bamboo & Cane", "en": "Basket", "hi": "टोकरी", "bn": "ঝুড়ি", "mr": "टोपली"},
    "mat": {"match": ["mat", "chatai", "चटाई", "মাদুর", "चटई"],
            "category": "Bamboo & Cane", "en": "Mat", "hi": "चटाई", "bn": "মাদুর", "mr": "चटई"},
    "box": {"match": ["box", "dibba", "डिब्बा", "बक्सा", "বাক্স", "पेटी"],
            "category": "Woodcraft", "en": "Box", "hi": "डिब्बा", "bn": "বাক্স", "mr": "पेटी"},
    "painting": {"match": ["painting", "chitra", "चित्र", "पेंटिंग", "ছবি", "चित्रकला"],
                 "category": "Paintings & Folk Art", "en": "Painting", "hi": "चित्र", "bn": "ছবি", "mr": "चित्र"},
    "wall_hanging": {"match": ["wall hanging", "toran", "तोरण", "দেওয়াল"],
                     "category": "Home Décor", "en": "Wall Hanging", "hi": "तोरण", "bn": "দেওয়াল সজ্জা", "mr": "तोरण"},
    "toy": {"match": ["toy", "khilona", "खिलौना", "খেলনা", "खेळणे"],
            "category": "Toys & Dolls", "en": "Toy", "hi": "खिलौना", "bn": "খেলনা", "mr": "खेळणे"},
    "doll": {"match": ["doll", "gudiya", "putli", "गुड़िया", "कठपुतली", "পুতুল", "बाहुली"],
             "category": "Toys & Dolls", "en": "Doll", "hi": "गुड़िया", "bn": "পুতুল", "mr": "बाहुली"},
    "chappal": {"match": ["chappal", "chappals", "चप्पल", "চপ্পল"],
                "category": "Leather", "en": "Chappals", "hi": "चप्पल", "bn": "চপ্পল", "mr": "चप्पल"},
    "footwear": {"match": ["jutti", "mojari", "जूती", "मोजड़ी"],
                 "category": "Leather", "en": "Juttis", "hi": "जूती", "bn": "জুতি", "mr": "चप्पल"},
    "bookmark": {"match": ["bookmark", "bookmarks", "बुकमार्क"],
                 "category": "Paintings & Folk Art", "en": "Bookmark", "hi": "बुकमार्क", "bn": "বুকমার্ক", "mr": "बुकमार्क"},
    "keychain": {"match": ["keychain", "key chain", "key ring", "चाबी का छल्ला", "कीचेन"],
                 "category": "Home Décor", "en": "Keychain", "hi": "चाबी का छल्ला", "bn": "চাবির রিং", "mr": "किचेन"},
    "ornament": {"match": ["ornament", "ornaments", "bauble", "सजावटी गोला"],
                 "category": "Home Décor", "en": "Ornament", "hi": "सजावटी लटकन", "bn": "অলংকার", "mr": "सजावटी लटकन"},
    "magnet": {"match": ["fridge magnet", "magnet", "मैग्नेट"],
               "category": "Home Décor", "en": "Fridge Magnet", "hi": "फ्रिज मैग्नेट", "bn": "ফ্রিজ ম্যাগনেট", "mr": "फ्रिज मॅग्नेट"},
    "pouch": {"match": ["pouch", "potli", "batua", "coin purse", "पोटली", "बटुआ"],
              "category": "Textiles & Handloom", "en": "Pouch", "hi": "बटुआ", "bn": "পাউচ", "mr": "बटवा"},
    "tray": {"match": ["tray", "thaal", "ट्रे"],
             "category": "Home Décor", "en": "Tray", "hi": "ट्रे", "bn": "ট্রে", "mr": "ट्रे"},
    "puppet": {"match": ["puppet", "puppets", "kathputli", "bommalata", "कठपुतली"],
               "category": "Toys & Dolls", "en": "Puppet", "hi": "कठपुतली", "bn": "পুতুল", "mr": "कठपुतळी"},
    "mask": {"match": ["mask", "mukhota", "मुखौटा"],
             "category": "Home Décor", "en": "Mask", "hi": "मुखौटा", "bn": "মুখোশ", "mr": "मुखवटा"},
    "spinning_top": {"match": ["spinning top", "lattu", "लट्टू"],
                     "category": "Toys & Dolls", "en": "Spinning Top", "hi": "लट्टू", "bn": "লাট্টু", "mr": "भोवरा"},
    "rug": {"match": ["rug", "dhurrie", "durrie", "dari", "दरी"],
            "category": "Textiles & Handloom", "en": "Dhurrie Rug", "hi": "दरी", "bn": "শতরঞ্চি", "mr": "सतरंजी"},
    "table_runner": {"match": ["table runner", "runner"],
                     "category": "Home Décor", "en": "Table Runner", "hi": "टेबल रनर", "bn": "টেবিল রানার", "mr": "टेबल रनर"},
    "hat": {"match": ["japi", "hat", "टोपी"],
            "category": "Bamboo & Cane", "en": "Japi Hat", "hi": "जापी टोपी", "bn": "জাপি টুপি", "mr": "जापी टोपी"},
    "pendant": {"match": ["pendant", "locket", "लॉकेट"],
                "category": "Jewellery", "en": "Pendant", "hi": "लॉकेट", "bn": "লকেট", "mr": "पेंडंट"},
    "jewellery_box": {"match": ["jewellery box", "jewelry box", "trinket box", "गहनों का डिब्बा"],
                      "category": "Home Décor", "en": "Trinket Box", "hi": "गहनों का डिब्बा", "bn": "গয়নার বাক্স", "mr": "दागिन्यांची पेटी"},
    "coaster": {"match": ["coaster", "coasters", "कोस्टर"],
                "category": "Stone Craft", "en": "Coaster Set", "hi": "कोस्टर", "bn": "কোস্টার", "mr": "कोस्टर"},
}

TECHNIQUES = {
    "hand_painted": {"match": ["hand painted", "hand-painted", "handpainted", "हाथ से पेंट", "हाथ से रंग", "হাতে আঁকা", "हाताने रंगवलेले"],
                     "en": "Hand-painted", "hi": "हाथ से चित्रित", "bn": "হাতে আঁকা", "mr": "हाताने रंगवलेले"},
    "blue_pottery": {"match": ["blue pottery", "नीली पॉटरी", "ब्लू पॉटरी", "नीले मिट्टी"],
                     "en": "Blue Pottery", "hi": "ब्लू पॉटरी", "bn": "ব্লু পটারি", "mr": "ब्लू पॉटरी", "gi": "Jaipur Blue Pottery"},
    "handloom": {"match": ["handloom", "hand woven", "handwoven", "हथकरघा", "हाथ से बुना", "তাঁত", "हातमाग"],
                 "en": "Handloom", "hi": "हथकरघा", "bn": "তাঁত", "mr": "हातमाग"},
    "block_print": {"match": ["block print", "block-print", "thappa", "ठप्पा", "ब्लॉक प्रिंट", "ব্লক প্রিন্ট"],
                    "en": "Hand Block-printed", "hi": "ठप्पा छपाई", "bn": "ব্লক প্রিন্ট", "mr": "ठसा छपाई"},
    "dhokra": {"match": ["dhokra", "dokra", "lost wax", "lost-wax", "ढोकरा", "डोकरा", "ডোকরা"],
               "en": "Dhokra", "hi": "ढोकरा", "bn": "ডোকরা", "mr": "ढोकरा", "gi": "Bastar Dhokra"},
    "embroidery": {"match": ["embroidery", "embroidered", "kadhai", "कढ़ाई", "কারুকাজ", "सूचिकर्म", "भरतकाम"],
                   "en": "Hand-embroidered", "hi": "कढ़ाई", "bn": "সূচিকর্ম", "mr": "भरतकाम"},
    "kantha": {"match": ["kantha", "कांथा", "কাঁথা স্টিচ", "কাঁথা"],
               "en": "Kantha Stitch", "hi": "कांथा", "bn": "কাঁথা", "mr": "कांथा", "gi": "Nakshi Kantha"},
    "terracotta": {"match": ["terracotta", "टेराकोटा", "পোড়ামাটি"],
                   "en": "Terracotta", "hi": "टेराकोटा", "bn": "পোড়ামাটি", "mr": "टेराकोटा"},
    "madhubani": {"match": ["madhubani", "mithila", "मधुबनी", "मिथिला"],
                  "en": "Madhubani", "hi": "मधुबनी", "bn": "মধুবনী", "mr": "मधुबनी", "gi": "Madhubani Paintings"},
    "warli": {"match": ["warli", "वारली"],
              "en": "Warli", "hi": "वारली", "bn": "ওয়ারলি", "mr": "वारली", "gi": "Warli Painting"},
    "pattachitra": {"match": ["pattachitra", "पटचित्र", "পটচিত্র"],
                    "en": "Pattachitra", "hi": "पटचित्र", "bn": "পটচিত্র", "mr": "पटचित्र", "gi": "Orissa Pattachitra"},
    "ikat": {"match": ["ikat", "pochampally", "इकत", "পোচমপল্লি"],
             "en": "Ikat", "hi": "इकत", "bn": "ইক্কত", "mr": "इकत", "gi": "Pochampally Ikat"},
    "bandhani": {"match": ["bandhani", "bandhej", "tie dye", "बांधनी", "बंधेज"],
                 "en": "Bandhani", "hi": "बंधेज", "bn": "বাঁধনি", "mr": "बांधणी"},
    "chikankari": {"match": ["chikankari", "chikan", "चिकनकारी", "चिकन"],
                   "en": "Chikankari", "hi": "चिकनकारी", "bn": "চিকনকারি", "mr": "चिकनकारी", "gi": "Lucknow Chikan Craft"},
    "carved": {"match": ["carved", "carving", "नक्काशी", "খোদাই", "कोरीव"],
               "en": "Hand-carved", "hi": "नक्काशीदार", "bn": "খোদাই করা", "mr": "कोरीव"},
    "wheel_thrown": {"match": ["wheel", "chaak", "चाक", "চাক"],
                     "en": "Wheel-thrown", "hi": "चाक पर बना", "bn": "চাকে তৈরি", "mr": "चाकावर घडवलेले"},
    "woven_cane": {"match": ["woven", "weaving", "बुनाई", "বোনা", "विणलेले"],
                   "en": "Hand-woven", "hi": "हाथ से बुना", "bn": "হাতে বোনা", "mr": "हाताने विणलेले"},
    "gond": {"match": ["gond", "गोंड"],
        "en": "Gond", "hi": "गोंड", "bn": "গোন্ড", "mr": "गोंड", "gi": "Gond Painting"},
    "kalamkari": {"match": ["kalamkari", "कलमकारी"],
        "en": "Kalamkari", "hi": "कलमकारी", "bn": "কলমকারি", "mr": "कलमकारी", "gi": "Srikalahasti Kalamkari"},
    "tanjore": {"match": ["tanjore", "thanjavur", "तंजौर"],
        "en": "Tanjore", "hi": "तंजौर", "bn": "তাঞ্জোর", "mr": "तंजौर", "gi": "Thanjavur Paintings"},
    "pichwai": {"match": ["pichwai", "pichhwai", "पिछवाई"],
        "en": "Pichwai", "hi": "पिछवाई", "bn": "পিছওয়াই", "mr": "पिछवाई"},
    "kalighat": {"match": ["kalighat", "कालीघाट", "কালীঘাট"],
        "en": "Kalighat", "hi": "कालीघाट", "bn": "কালীঘাট", "mr": "कालीघाट"},
    "phulkari": {"match": ["phulkari", "फुलकारी"],
        "en": "Phulkari", "hi": "फुलकारी", "bn": "ফুলকারি", "mr": "फुलकारी", "gi": "Phulkari"},
    "banarasi": {"match": ["banarasi", "benarasi", "बनारसी"],
        "en": "Banarasi", "hi": "बनारसी", "bn": "বেনারসি", "mr": "बनारसी", "gi": "Banaras Brocades and Sarees"},
    "pashmina": {"match": ["pashmina", "पश्मीना"],
        "en": "Pashmina", "hi": "पश्मीना", "bn": "পশমিনা", "mr": "पश्मीना", "gi": "Kashmir Pashmina"},
    "kutch_embroidery": {"match": ["kutch embroidery", "kutchi", "mirror work", "कच्छी कढ़ाई", "शीशे का काम"],
        "en": "Kutch Mirror-work", "hi": "कच्छी कढ़ाई", "bn": "কচ্ছ সূচিকর্ম", "mr": "कच्छी भरतकाम", "gi": "Kutch Embroidery"},
    "zardozi": {"match": ["zardozi", "zardosi", "जरदोज़ी", "जरदोजी"],
        "en": "Zardozi", "hi": "ज़रदोज़ी", "bn": "জরদৌসি", "mr": "जरदोजी", "gi": "Lucknow Zardozi"},
    "bidri": {"match": ["bidri", "bidriware", "बिदरी"],
        "en": "Bidri", "hi": "बिदरी", "bn": "বিদরি", "mr": "बिदरी", "gi": "Bidriware"},
    "moradabad_brass": {"match": ["moradabad", "मुरादाबादी"],
        "en": "Moradabad Brass", "hi": "मुरादाबादी पीतल", "bn": "মোরাদাবাদি", "mr": "मुरादाबादी", "gi": "Moradabad Metal Craft"},
    "meenakari": {"match": ["meenakari", "minakari", "enamel", "मीनाकारी"],
        "en": "Meenakari", "hi": "मीनाकारी", "bn": "মীনাকারি", "mr": "मीनाकारी"},
    "filigree": {"match": ["filigree", "tarakasi", "तारकशी"],
        "en": "Silver Filigree", "hi": "चांदी तारकशी", "bn": "রুপোর তারকাজ", "mr": "चांदी तारकाम", "gi": "Cuttack Rupa Tarakasi"},
    "kondapalli": {"match": ["kondapalli", "कोंडापल्ली"],
        "en": "Kondapalli", "hi": "कोंडापल्ली", "bn": "কোন্ডাপল্লি", "mr": "कोंडापल्ली", "gi": "Kondapalli Bommallu"},
    "saharanpur": {"match": ["saharanpur", "सहारनपुरी"],
        "en": "Saharanpur", "hi": "सहारनपुरी", "bn": "সাহারানপুরি", "mr": "सहारनपुरी", "gi": "Saharanpur Wood Craft"},
    "sandalwood": {"match": ["sandalwood", "chandan", "चंदन"],
        "en": "Sandalwood", "hi": "चंदन", "bn": "চন্দন", "mr": "चंदन"},
    "longpi": {"match": ["longpi", "black pottery", "लोंगपी"],
        "en": "Longpi Black", "hi": "लोंगपी काली मिट्टी", "bn": "লংপি", "mr": "लोंगपी"},
    "bankura": {"match": ["bankura", "panchmura", "बांकुड़ा", "বাঁকুড়া"],
        "en": "Bankura", "hi": "बांकुड़ा", "bn": "বাঁকুড়া", "mr": "बांकुरा", "gi": "Bankura Panchmura Terracotta Craft"},
    "sikki": {"match": ["sikki", "सिक्की"],
        "en": "Sikki Grass", "hi": "सिक्की घास", "bn": "সিক্কি", "mr": "सिक्की घास", "gi": "Sikki Grass Products of Bihar"},
    "assam_cane": {"match": ["assam cane", "assamese", "असमिया"],
        "en": "Assam Cane", "hi": "असमिया बेंत", "bn": "অসমীয়া বেত", "mr": "आसामी वेत"},
    "kolhapuri": {"match": ["kolhapuri", "कोल्हापुरी"],
        "en": "Kolhapuri", "hi": "कोल्हापुरी", "bn": "কোলাপুরি", "mr": "कोल्हापुरी", "gi": "Kolhapuri Chappal"},
    "leather_puppet": {"match": ["tholu bommalata", "leather puppet", "shadow puppet", "तोलु बोम्मलाटा"],
        "en": "Tholu Bommalata", "hi": "तोलु बोम्मलाटा", "bn": "তোলু বোম্মালাটা", "mr": "तोलु बोम्मलाटा", "gi": "Andhra Pradesh Leather Puppetry"},
    "mamallapuram": {"match": ["mamallapuram", "mahabalipuram", "महाबलीपुरम"],
        "en": "Mamallapuram Stone", "hi": "महाबलीपुरम पत्थर", "bn": "মামাল্লাপুরম", "mr": "महाबलीपुरम", "gi": "Mamallapuram Stone Sculpture"},
    "marble_inlay": {"match": ["marble inlay", "pietra dura", "parchin kari", "पच्चीकारी"],
        "en": "Marble Inlay", "hi": "पच्चीकारी", "bn": "মার্বেল ইনলে", "mr": "पच्चीकारी"},
    "kathputli": {"match": ["kathputli", "कठपुतली"],
        "en": "Rajasthani", "hi": "राजस्थानी", "bn": "রাজস্থানী", "mr": "राजस्थानी"},
    "papier_mache": {"match": ["papier mache", "papier-mache", "paper mache", "पेपर माशी"],
        "en": "Kashmiri Papier-mâché", "hi": "कश्मीरी पेपर माशी", "bn": "কাশ্মীরি পেপার মাশে", "mr": "काश्मिरी पेपर माशे", "gi": "Kashmir Paper Machie"},
    "navalgund": {"match": ["navalgund", "नवलगुंद"],
        "en": "Navalgund", "hi": "नवलगुंद", "bn": "নবলগুন্দ", "mr": "नवलगुंद", "gi": "Navalgund Durries"},
    "lac_craft": {"match": ["lac bangle", "lac bangles", "lac work", "लाख की चूड़ी", "लाख की चूड़ियाँ"],
        "en": "Lac", "hi": "लाख", "bn": "গালা", "mr": "लाख"},
    "jute_craft": {"match": ["jute craft", "jute work", "पटसन शिल्प"],
        "en": "Jute", "hi": "जूट", "bn": "পাট", "mr": "ताग"},
    "channapatna": {"match": ["channapatna", "चन्नपटना"],
                    "en": "Channapatna", "hi": "चन्नपटना", "bn": "চন্নপাটনা", "mr": "चन्नपटना", "gi": "Channapatna Toys & Dolls"},
}

MATERIALS = {
    "cotton": {"match": ["cotton", "sooti", "सूती", "कपास", "সুতি", "सुती"], "en": "Cotton", "hi": "सूती", "bn": "সুতি", "mr": "सुती"},
    "silk": {"match": ["silk", "resham", "रेशम", "रेशमी", "সিল্ক", "রেশম"], "en": "Silk", "hi": "रेशम", "bn": "রেশম", "mr": "रेशीम"},
    "wool": {"match": ["wool", "woollen", "ऊन", "ऊनी", "পশম"], "en": "Wool", "hi": "ऊन", "bn": "পশম", "mr": "लोकर"},
    "clay": {"match": ["clay", "mitti", "मिट्टी", "মাটি", "माती"], "en": "Clay", "hi": "मिट्टी", "bn": "মাটি", "mr": "माती"},
    "quartz": {"match": ["quartz", "क्वार्ट्ज"], "en": "Quartz", "hi": "क्वार्ट्ज", "bn": "কোয়ার্টজ", "mr": "क्वार्ट्झ"},
    "brass": {"match": ["brass", "peetal", "pital", "पीतल", "পিতল", "पितळ"], "en": "Brass", "hi": "पीतल", "bn": "পিতল", "mr": "पितळ"},
    "bronze": {"match": ["bronze", "kansa", "कांसा", "কাঁসা"], "en": "Bronze", "hi": "कांसा", "bn": "কাঁসা", "mr": "कांस्य"},
    "copper": {"match": ["copper", "tamba", "तांबा", "তামা"], "en": "Copper", "hi": "तांबा", "bn": "তামা", "mr": "तांबे"},
    "silver": {"match": ["silver", "chandi", "चांदी", "চাঁদি", "रुपे"], "en": "Silver", "hi": "चांदी", "bn": "রুপো", "mr": "चांदी"},
    "wood": {"match": ["wood", "wooden", "lakdi", "लकड़ी", "কাঠ", "लाकूड"], "en": "Wood", "hi": "लकड़ी", "bn": "কাঠ", "mr": "लाकूड"},
    "bamboo": {"match": ["bamboo", "baans", "बांस", "बाँस", "বাঁশ", "बांबू"], "en": "Bamboo", "hi": "बाँस", "bn": "বাঁশ", "mr": "बांबू"},
    "cane": {"match": ["cane", "rattan", "बेंत", "বেত", "वेत"], "en": "Cane", "hi": "बेंत", "bn": "বেত", "mr": "वेत"},
    "jute": {"match": ["jute", "जूट", "पटसन", "পাট"], "en": "Jute", "hi": "जूट", "bn": "পাট", "mr": "ताग"},
    "leather": {"match": ["leather", "chamda", "चमड़ा", "চামড়া", "चामडे"], "en": "Leather", "hi": "चमड़ा", "bn": "চামড়া", "mr": "चामडे"},
    "stone": {"match": ["stone", "patthar", "पत्थर", "পাথর", "दगड"], "en": "Stone", "hi": "पत्थर", "bn": "পাথর", "mr": "दगड"},
    "marble": {"match": ["marble", "sangmarmar", "संगमरमर", "মার্বেল"], "en": "Marble", "hi": "संगमरमर", "bn": "মার্বেল", "mr": "संगमरवर"},
    "beads": {"match": ["beads", "bead", "moti", "मोती", "পুঁতি", "मणी"], "en": "Beads", "hi": "मोती", "bn": "পুঁতি", "mr": "मणी"},
    "paper": {"match": ["paper", "papier mache", "कागज़", "कागज", "কাগজ"], "en": "Paper", "hi": "कागज़", "bn": "কাগজ", "mr": "कागद"},
    "natural_dye": {"match": ["natural dye", "natural colour", "natural color", "प्राकृतिक रंग", "প্রাকৃতিক রং"],
                    "en": "Natural dyes", "hi": "प्राकृतिक रंग", "bn": "প্রাকৃতিক রং", "mr": "नैसर्गिक रंग"},
    "lac": {"match": ["lac", "lacquer", "लाख", "গালা"], "en": "Lac", "hi": "लाख", "bn": "গালা", "mr": "लाख"},
}

COLORS = {
    "blue": {"match": ["blue", "neela", "नीला", "नीली", "नीले", "নীল", "निळा"], "en": "Blue", "hi": "नीला", "bn": "নীল", "mr": "निळा"},
    "red": {"match": ["red", "laal", "लाल", "লাল"], "en": "Red", "hi": "लाल", "bn": "লাল", "mr": "लाल"},
    "green": {"match": ["green", "hara", "हरा", "हरी", "সবুজ", "हिरवा"], "en": "Green", "hi": "हरा", "bn": "সবুজ", "mr": "हिरवा"},
    "yellow": {"match": ["yellow", "peela", "पीला", "पीली", "হলুদ", "पिवळा"], "en": "Yellow", "hi": "पीला", "bn": "হলুদ", "mr": "पिवळा"},
    "white": {"match": ["white", "safed", "सफ़ेद", "सफेद", "সাদা", "पांढरा"], "en": "White", "hi": "सफ़ेद", "bn": "সাদা", "mr": "पांढरा"},
    "black": {"match": ["black", "kaala", "काला", "काली", "কালো", "काळा"], "en": "Black", "hi": "काला", "bn": "কালো", "mr": "काळा"},
    "orange": {"match": ["orange", "narangi", "नारंगी", "केसरिया", "কমলা", "केशरी"], "en": "Orange", "hi": "नारंगी", "bn": "কমলা", "mr": "केशरी"},
    "pink": {"match": ["pink", "gulabi", "गुलाबी", "গোলাপি"], "en": "Pink", "hi": "गुलाबी", "bn": "গোলাপি", "mr": "गुलाबी"},
    "maroon": {"match": ["maroon", "मैरून", "মেরুন"], "en": "Maroon", "hi": "मैरून", "bn": "মেরুন", "mr": "मरून"},
    "gold": {"match": ["gold", "golden", "sunehra", "सुनहरा", "सोनेरी", "সোনালি"], "en": "Golden", "hi": "सुनहरा", "bn": "সোনালি", "mr": "सोनेरी"},
    "indigo": {"match": ["indigo", "ইন্ডিগো"], "en": "Indigo", "hi": "नील", "bn": "নীল", "mr": "नीळ"},
}

# GI crafts -> home region, used for the GI/cluster premium and certificate text.
GI_CRAFTS = {
    "Jaipur Blue Pottery": "Rajasthan",
    "Bastar Dhokra": "Chhattisgarh",
    "Nakshi Kantha": "West Bengal",
    "Madhubani Paintings": "Bihar",
    "Warli Painting": "Maharashtra",
    "Orissa Pattachitra": "Odisha",
    "Pochampally Ikat": "Telangana",
    "Lucknow Chikan Craft": "Uttar Pradesh",
    "Channapatna Toys & Dolls": "Karnataka",
    "Bagru Hand Block Print": "Rajasthan",
    "Sanganeri Hand Block Printing": "Rajasthan",
    "Santipore Saree": "West Bengal",
    "Dhaniakhali Saree": "West Bengal",
    "Kota Doria": "Rajasthan",
    "Chanderi Fabric": "Madhya Pradesh",
    "Banaras Brocades and Sarees": "Uttar Pradesh",
    "Gond Painting": "Madhya Pradesh",
    "Srikalahasti Kalamkari": "Andhra Pradesh",
    "Thanjavur Paintings": "Tamil Nadu",
    "Phulkari": "Punjab",
    "Kashmir Pashmina": "Jammu and Kashmir",
    "Kutch Embroidery": "Gujarat",
    "Lucknow Zardozi": "Uttar Pradesh",
    "Bidriware": "Karnataka",
    "Moradabad Metal Craft": "Uttar Pradesh",
    "Cuttack Rupa Tarakasi": "Odisha",
    "Kondapalli Bommallu": "Andhra Pradesh",
    "Saharanpur Wood Craft": "Uttar Pradesh",
    "Bankura Panchmura Terracotta Craft": "West Bengal",
    "Sikki Grass Products of Bihar": "Bihar",
    "Kolhapuri Chappal": "Maharashtra",
    "Andhra Pradesh Leather Puppetry": "Andhra Pradesh",
    "Mamallapuram Stone Sculpture": "Tamil Nadu",
    "Kashmir Paper Machie": "Jammu and Kashmir",
    "Navalgund Durries": "Karnataka",
}

STATES = [
    "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana",
    "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
    "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana",
    "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", "Delhi", "Jammu and Kashmir", "Ladakh",
]

PLACES = {
    "jaipur": ("Jaipur", "Rajasthan"), "जयपुर": ("Jaipur", "Rajasthan"),
    "bastar": ("Bastar", "Chhattisgarh"), "बस्तर": ("Bastar", "Chhattisgarh"),
    "khunti": ("Khunti", "Jharkhand"), "खूंटी": ("Khunti", "Jharkhand"),
    "shantipur": ("Shantipur", "West Bengal"), "santipur": ("Shantipur", "West Bengal"), "শান্তিপুর": ("Shantipur", "West Bengal"),
    "phulia": ("Phulia", "West Bengal"), "ফুলিয়া": ("Phulia", "West Bengal"),
    "bagru": ("Bagru", "Rajasthan"), "बगरू": ("Bagru", "Rajasthan"),
    "madhubani": ("Madhubani", "Bihar"), "मधुबनी": ("Madhubani", "Bihar"),
    "lucknow": ("Lucknow", "Uttar Pradesh"), "लखनऊ": ("Lucknow", "Uttar Pradesh"),
    "varanasi": ("Varanasi", "Uttar Pradesh"), "banaras": ("Varanasi", "Uttar Pradesh"), "बनारस": ("Varanasi", "Uttar Pradesh"),
    "kutch": ("Kutch", "Gujarat"), "कच्छ": ("Kutch", "Gujarat"),
    "channapatna": ("Channapatna", "Karnataka"),
    "raghurajpur": ("Raghurajpur", "Odisha"),
    "patangarh": ("Patangarh", "Madhya Pradesh"), "dindori": ("Dindori", "Madhya Pradesh"),
    "srikalahasti": ("Srikalahasti", "Andhra Pradesh"), "thanjavur": ("Thanjavur", "Tamil Nadu"),
    "nathdwara": ("Nathdwara", "Rajasthan"), "patiala": ("Patiala", "Punjab"), "srinagar": ("Srinagar", "Jammu and Kashmir"),
    "bhuj": ("Bhuj", "Gujarat"), "bidar": ("Bidar", "Karnataka"), "moradabad": ("Moradabad", "Uttar Pradesh"),
    "cuttack": ("Cuttack", "Odisha"), "kondapalli": ("Kondapalli", "Andhra Pradesh"),
    "saharanpur": ("Saharanpur", "Uttar Pradesh"), "mysuru": ("Mysuru", "Karnataka"), "mysore": ("Mysuru", "Karnataka"),
    "ukhrul": ("Ukhrul", "Manipur"), "longpi": ("Longpi", "Manipur"), "bankura": ("Bankura", "West Bengal"),
    "kolhapur": ("Kolhapur", "Maharashtra"), "nimmalakunta": ("Nimmalakunta", "Andhra Pradesh"),
    "mamallapuram": ("Mamallapuram", "Tamil Nadu"), "agra": ("Agra", "Uttar Pradesh"),
    "navalgund": ("Navalgund", "Karnataka"), "kolkata": ("Kolkata", "West Bengal"), "jorhat": ("Jorhat", "Assam"),
}

# Spoken number words (small, extendable). Values are integers.
NUMBER_WORDS = {
    # English
    "one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6, "seven": 7, "eight": 8, "nine": 9,
    "ten": 10, "eleven": 11, "twelve": 12, "fifteen": 15, "twenty": 20, "thirty": 30, "forty": 40,
    "fifty": 50, "hundred": 100, "thousand": 1000, "a": 1, "an": 1,
    "thirteen": 13, "fourteen": 14, "sixteen": 16, "seventeen": 17, "eighteen": 18, "nineteen": 19,
    "sixty": 60, "seventy": 70, "eighty": 80, "ninety": 90,
    "ग्यारह": 11, "तेरह": 13, "चौदह": 14, "सोलह": 16, "सत्रह": 17, "अठारह": 18, "उन्नीस": 19,
    "पच्चीस": 25, "साठ": 60, "सत्तर": 70, "अस्सी": 80, "नब्बे": 90,
    "solah": 16, "satrah": 17, "athaarah": 18, "pachchees": 25, "saath": 60, "assi": 80,
    # Hindi (Devanagari + romanised)
    "एक": 1, "दो": 2, "तीन": 3, "चार": 4, "पांच": 5, "पाँच": 5, "छह": 6, "छः": 6, "सात": 7, "आठ": 8,
    "नौ": 9, "दस": 10, "बारह": 12, "पंद्रह": 15, "बीस": 20, "तीस": 30, "चालीस": 40, "पचास": 50,
    "सौ": 100, "हज़ार": 1000, "हजार": 1000, "डेढ़": 1.5, "ढाई": 2.5,
    "ek": 1, "do": 2, "teen": 3, "char": 4, "paanch": 5, "panch": 5, "chhe": 6, "saat": 7, "aath": 8,
    "nau": 9, "das": 10, "baarah": 12, "pandrah": 15, "bees": 20, "tees": 30, "pachaas": 50,
    "sau": 100, "hazaar": 1000, "hazar": 1000,
    # Bengali
    "এক": 1, "দুই": 2, "তিন": 3, "চার": 4, "পাঁচ": 5, "ছয়": 6, "সাত": 7, "আট": 8, "নয়": 9, "দশ": 10,
    "শ": 100, "হাজার": 1000,
    # Marathi (where different from Hindi)
    "दोन": 2, "पाच": 5, "सहा": 6, "नऊ": 9, "शंभर": 100,
}

UNIT_WORDS = {
    "days": ["day", "days", "din", "दिन", "দিন", "दिवस"],
    "hours": ["hour", "hours", "hr", "hrs", "ghante", "ghanta", "घंटे", "घंटा", "ঘণ্টা", "तास"],
    "weeks": ["week", "weeks", "hafte", "hafta", "हफ्ते", "हफ़्ते", "सप्ताह", "সপ্তাহ", "आठवडे"],
    "rupees": ["rupees", "rupee", "rs", "₹", "inr", "rupaye", "rupay", "रुपये", "रुपए", "रुपया", "টাকা", "रुपये"],
    "cm": ["cm", "centimeter", "centimetre", "सेंटीमीटर", "सेमी", "সেমি"],
    "inch": ["inch", "inches", "इंच", "ইঞ্চি"],
    "grams": ["gram", "grams", "g", "gm", "ग्राम", "গ্রাম"],
    "kg": ["kg", "kilo", "kilogram", "किलो", "কেজি"],
    "meters": ["meter", "meters", "metre", "metres", "m", "मीटर", "মিটার"],
    "pieces": ["pieces", "piece", "pcs", "pc", "पीस", "नग", "पिस", "টি", "পিস"],
}

# Cue words that attach a number to a slot.
COST_CUES = ["material", "materials", "cost", "saamaan", "samaan", "saman", "सामान", "सामग्री", "लागत", "खर्च",
             "कच्चा माल", "উপকরণ", "খরচ", "माल"]
PRICE_CUES = ["sell", "price", "daam", "keemat", "दाम", "कीमत", "बेचना", "बेचूंगी", "দাম", "किंमत"]
QTY_CUES = ["quantity", "stock", "available", "have", "बने हैं", "तैयार", "हैं मेरे पास", "আছে", "आहेत"]
HEIGHT_CUES = ["tall", "height", "high", "ऊंचा", "ऊँचा", "ऊंचाई", "লম্বা", "उंच"]
WIDTH_CUES = ["wide", "width", "चौड़ा", "चौड़ाई", "চওড়া", "रुंद"]
LENGTH_CUES = ["long", "length", "लंबा", "लम्बा", "लंबाई", "দৈর্ঘ্য", "लांब"]

CARE = {
    "Pottery & Ceramics": {"en": "Wipe with a soft dry cloth. Not for microwave or dishwasher.",
                           "hi": "मुलायम सूखे कपड़े से पोंछें। माइक्रोवेव या डिशवॉशर में न डालें।"},
    "Textiles & Handloom": {"en": "Gentle hand wash in cold water or dry clean. Dry in shade.",
                            "hi": "ठंडे पानी में हल्के हाथ से धोएं या ड्राई क्लीन कराएं। छाया में सुखाएं।"},
    "Metalcraft": {"en": "Dust with a dry cloth. Polish occasionally with tamarind or lemon.",
                   "hi": "सूखे कपड़े से साफ़ करें। कभी-कभी इमली या नींबू से चमकाएं।"},
    "Woodcraft": {"en": "Keep away from moisture. Wipe with a dry cloth.",
                  "hi": "नमी से दूर रखें। सूखे कपड़े से पोंछें।"},
    "Bamboo & Cane": {"en": "Keep dry; air in sunlight occasionally.", "hi": "सूखा रखें; कभी-कभी धूप दिखाएं।"},
    "Jewellery": {"en": "Keep away from water and perfume. Store in a pouch.",
                  "hi": "पानी और इत्र से दूर रखें। थैली में रखें।"},
    "Paintings & Folk Art": {"en": "Keep away from direct sunlight and moisture.",
                             "hi": "सीधी धूप और नमी से दूर रखें।"},
    "Leather": {"en": "Wipe clean; condition occasionally.", "hi": "साफ़ कपड़े से पोंछें; कभी-कभी तेल लगाएं।"},
    "Stone Craft": {"en": "Wipe with a damp cloth.", "hi": "गीले कपड़े से पोंछें।"},
    "Toys & Dolls": {"en": "Wipe with a dry cloth. Keep dry.", "hi": "सूखे कपड़े से पोंछें। सूखा रखें।"},
    "Home Décor": {"en": "Dust gently with a soft cloth.", "hi": "मुलायम कपड़े से धीरे से धूल साफ़ करें।"},
    "Other": {"en": "Handle with care.", "hi": "सावधानी से रखें।"},
}
